server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: aaaa
    password: bbbb
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  data:
    redis:
      host: cccc
      port: 6379
      password: dddd
      database: 0

  rabbitmq:
    host: 119.91.231.127
    port: 5672
    username: rabbitmq
    password: 4dzTrtmMr5KLzzc3
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2
          max-interval: 10000
          max-retries: 3

  # 禁用Redisson自动配置
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration

  mail:
    host: smtp.qq.com
    port: 465
    username: eeee
    password: ffff
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.qq.com

app:
  jwt:
    issuer: security-demo
    access-token-ttl: 3d
    refresh-token-ttl: 7d

    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32_BYTES_MIN_CHANGE_ME"
    expiration-seconds: 259200

  token:
    redis-prefix: "login:token:"
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:5175"
      - "http://localhost:8080"
  # 与 sys_roles.name 一致；无权限的用户访问对应 API 将返回 403
  security:
    cinema-api-roles:
      - SUPER_ADMIN
      - ADMIN
      - STAFF
      - USER
    movie-api-roles:
      - SUPER_ADMIN
      - ADMIN
      - STAFF
      - USER
    order-api-roles:
      - SUPER_ADMIN
      - ADMIN
      - STAFF
      - USER
    user-api-roles:
      - SUPER_ADMIN
      - ADMIN
    settings-api-roles:
      - SUPER_ADMIN
      - ADMIN
      - STAFF
      - USER

# MinIO配置
minio:
  endpoint: http://119.91.231.127:19000
  access-key: minio
  secret-key: HZpk6nwHiMY6KJxx
  bucket-name: cinema-movies
  url-prefix: http://119.91.231.127:19000/cinema-movies


mybatis-plus:
  type-aliases-package: org.tonyqwe.cinemaweb.domain.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
